apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ${REPO_NAME}
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 3
  schedule: "0 22 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ${REPO_NAME}
            image: ${ECR_REGISTRY}/${REPO_NAME}:${TAG_IMAGE}
            envFrom:
            - secretRef:
                name: ${REPO_NAME}-secret
          restartPolicy: OnFailure
          nodeSelector:
            eks.amazonaws.com/nodegroup: eks-tool-node-group-${ENV_REF}
          tolerations:
          - key: "tool"
            operator: "Exists"
            effect: "NoSchedule"
      backoffLimit: 3
