name: "Adiciona Issues em Projects GitHub"
  
on:
  push:
    branches:
      - "master"
jobs:
  add-issue:
    uses: "EzzioMoreira/lab-actions/.github/workflows/add-projects.yaml@master"
    with:
      project_url: "https://github.com/users/EzzioMoreira/projects/2"
      token: ${{ secrets.API_TOKEN_GITHUB }}

