name: "Adiciona Issues em Projects GitHub"
  
on:
  push:
    branches:
      - "master"
jobs:
  add-issue:
    uses: "EzzioMoreira/cicd_centralizado/.github/workflows/add_issues_projects.yaml@feat/add-actions-projects"
    with:
      project_url: https://github.com/orgs/mentoriaiac/projects/6
    secrets:  
      token: ${{ secrets.API_TOKEN_GITHUB }}
