name: Teste com Matrix

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      task: ${{ steps.set-matrix.outputs.task }}
    steps:
      - id: set-matrix
        run: | 
          echo "::set-output name=task::[1, 2]"
         
  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    env:
      TASK: ${{ fromJson(needs.job1.outputs.task) }}
    steps:
      - run: |
          echo $TASK
          echo ${{github.repository}}
          echo $github.repository
