name: Teste com Matrix

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  task: live_db
  service: ddog-postgres

jobs:
         
  job1:
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $TASK
          echo ${{github.repository}}
          echo $github.repository
          echo ${{env.task}}
          echo ${{env.service}}
          echo ${{GITHUB_JOB}}
          echo ${{GITHUB.JOB}}
