name: Teste com Matrix

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  service: ddog-agent
  env: stg

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: | 
          echo "::set-output name=matrix::[10, 12, 14]"
         
  live_db:
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $TASK
          echo ${{github.repository}}
          echo $github.repository
          echo ${{env.task}}-${{env.task}}-${{GITHUB.JOB}}
          echo ${{env.service}}
          echo ${{GITHUB.JOB}}
